# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3c9305094d7992a5deddd8bbce269e10faccdf7ab68acbf812a3c68846a3e702530d4d9557b5b4f873a51c667ab1348c51b0fbcd651f8e7c0551f8592cc386

test:
  secret_key_base: faee53f6b2397bc3a4830f03c48c81997694b9555d17461da796cb131e901492b44143cbf29abfb8dba105c0a2ebe66c8fb6d5bc3ec384ffb899273b0c880f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
